### ISSUE TITLE
Failed to extract with JCV RO Tools, please assist.

### ISSUE THREAD

**Issue by kikilalar** [fadreus/JCV-s-RO-Tools-1.0.3#1]
![image](https://user-images.githubusercontent.com/22374459/42153732-94c57962-7e16-11e8-8fd2-ff4a251bd9e5.png)

Had been trying to extract recvpackets.txt from this official server of RE:Start, SG/MY, Thor, but no luck on using different tools. 

Wish to seek assistance regarding with the error returned, when I was trying to extract recvpackets.txt.

Please help, thank you.

**Comment by Fadreus** [comment]
If you're not software developer / engineer, you can't make this work for MY/SG server.
The expert also having trouble with this.
Unless you are in same caliber as them, just give up.
